### ISSUE TITLE
How to open TCP and UDP ports for multiplayer?

### ISSUE THREAD

**Issue by meetcshah19** [jh62/BattleCityMultiplayer#1]
I was trying to play the multiplayer mode over the internet but couldn’t establish the connection. I did change my config file to open the TCP/UDP ports but am not sure how exactly do they work.

**Comment by jh62** [comment]
If you are behind a router, then portforwarding it was you should do in the router's interface. If you can't play still, i recommend that you use a software like Parsecs (https://parsecgaming.com/) that works great.
